// Grabbing HTML //
var cityChoiceEl = $("#cityChoice")
var cityListEl = $(".cityList")
var cityInfoEl = $(".cityInfo")
var cityNameEl = $(".cityName")
var todayImgEl = $(".todayImg")
var tempEl = $(".temp")
var humidEl = $(".humidity")
var windEl = $(".windSpeed")
var uvIndexEl = $(".uvIndex")
var forecastDate0 = $(".forecastDate0")
var forecastDate1 = $(".forecastDate1")
var forecastDate2 = $(".forecastDate2")
var forecastDate3 = $(".forecastDate3")
var forecastDate4 = $(".forecastDate4")
var forecastTemp0 = $(".forecastTemp0")
var forecastTemp1 = $(".forecastTemp1")
var forecastTemp2 = $(".forecastTemp2")
var forecastTemp3 = $(".forecastTemp3")
var forecastTemp4 = $(".forecastTemp4")
var forecastHumidity0 = $(".forecastHumidity0")
var forecastHumidity1 = $(".forecastHumidity1")
var forecastHumidity2 = $(".forecastHumidity2")
var forecastHumidity3 = $(".forecastHumidity3")
var forecastHumidity4 = $(".forecastHumidity4")

// URLs //
var requestUrl = `api.openweathermap.org/data/2.5/weather?q=${cityName}&appid=bdf166e3737ee21dc0f6661d8925ff12`